export const allProducts = [
  {
    id: 1,
    name: "Product One",
    slug: "product-one",
    tagLine: "The first product",
    description: "This is the description for Product One.",
    websiteUrl: "https://productone.com",
    tags: ["tag1", "tag2"],
    voteCount: 10,
    status: "approved",
    submittedBy: "Alice",
    createdAt: new Date("2023-01-01T10:00:00Z"),
    approvedAt: new Date("2023-01-02T10:00:00Z"),
  },
  {
    id: 2,
    name: "Product Two",
    slug: "product-two",
    tagLine: "The second product",
    description: "This is the description for Product Two.",
    websiteUrl: "https://producttwo.com",
    tags: ["tag3", "tag4"],
    voteCount: 5,
    status: "pending",
    submittedBy: "Bob",
    createdAt: new Date("2023-02-01T10:00:00Z"),
    approvedAt: new Date("2023-02-03T10:00:00Z"),
  },
];
